#!/usr/bin/env python3
import argparse, tempfile, subprocess, os
parser = argparse.ArgumentParser()
parser.add_argument("-p", "--port", type=int, default=5004)
args = parser.parse_args()

try:
    import netifaces
    for addr in filter(lambda x: not x.startswith('127'), filter(None, [item.get('addr') for sublist in [netifaces.ifaddresses(iface).get(netifaces.AF_INET, []) for iface in netifaces.interfaces()] for item in sublist])):
        uri = 'http://{}:{}'.format(addr, args.port)
        print(uri)
        try:
            import qrcode
            qr = qrcode.QRCode()
            qr.add_data(uri)
            qr.print_ascii(tty=True)
        except ImportError:
            pass
except ImportError:
    pass

conffd, conffile = tempfile.mkstemp(suffix="hostmenow")
os.close(conffd) # because it's idiotic
with open(conffile, "w") as f:
    f.write("""
server.document-root = "%s"
server.port = %i
mimetype.assign = (
  ".html" => "text/html",
  ".txt" => "text/plain",
  ".css" => "text/css",
  ".js" => "text/javascript",
  ".jpg" => "image/jpeg",
  ".png" => "image/png",
  ".webp" => "image/webp",
  ".svg" => "image/svg+xml"
)
dir-listing.activate = "enable"
""" % (os.getcwd(), args.port))
assert subprocess.call(["lighttpd", "-t", "-f", conffile]) == 0
subprocess.call(["lighttpd", "-D", "-f", conffile])
os.remove(conffile)
